#!/usr/bin/env bash
# Gives one coding agent its own place to work (CLAUDE.md §17):
#   - a git worktree on a new branch feature/<name>, cut from the latest origin/main,
#   - its own schema agent_<name> in contractor_agent_dev, a second database in the one database
#     container (never contractor_agent, the production one), migrated and seeded with fictional data,
#   - its own .env: every setting from the main checkout's .env except that the database points at that
#     schema, every scheduled or sending job is off, and no Outlook credential is copied,
#   - its own dev-server port in .dev-port, used by `npm run dev:wt`.
#
#   ./scripts/new-worktree.sh <name>        e.g. ./scripts/new-worktree.sh resume-search
#   WORKTREE_BASE=<ref> ./scripts/new-worktree.sh <name>   start from another ref (for testing)
set -euo pipefail

name="${1:-}"
if ! printf '%s' "$name" | grep -Eq '^[a-z][a-z0-9-]{1,30}$'; then
  echo "Usage: $0 <name>   (lowercase letters, digits and dashes, starting with a letter)" >&2
  exit 2
fi

main_dir=$(cd "$(git rev-parse --git-common-dir)/.." && pwd)
root="${CONTRACT_AGENT_WORKTREES:-$(dirname "$main_dir")/contractJobAgent-worktrees}"
dir="$root/$name"
schema="agent_$(printf '%s' "$name" | tr '-' '_')"
[ -e "$dir" ] && { echo "$dir already exists." >&2; exit 1; }
[ -e "$main_dir/.env" ] || { echo "No .env in $main_dir to start from." >&2; exit 1; }

# The worktree uses the main .env's database account and server, pointed at contractor_agent_dev
# instead of the production database, in its own schema.
url=$(node -e '
  require("dotenv").config({ path: process.argv[1], quiet: true });
  const url = new URL(process.env.DATABASE_URL);
  url.pathname = "/contractor_agent_dev";
  url.searchParams.set("schema", process.argv[2]);
  console.log(url.toString());
' "$main_dir/.env" "$schema")
db_user=$(node -e 'console.log(decodeURIComponent(new URL(process.argv[1]).username))' "$url")
# Created once, in the same container as production.
if ! docker exec contractor-agent-db psql -tA -U "$db_user" -d postgres -c "select 1 from pg_database where datname='contractor_agent_dev'" | grep -q 1; then
  docker exec contractor-agent-db psql -q -U "$db_user" -d postgres -c "CREATE DATABASE contractor_agent_dev"
fi

git -C "$main_dir" fetch --quiet origin main
mkdir -p "$root"
git -C "$main_dir" worktree add --quiet -b "feature/$name" "$dir" "${WORKTREE_BASE:-origin/main}"

# First free port from 3101, skipping other worktrees' ports and anything already listening.
port=3101
while grep -qx "$port" "$root"/*/.dev-port 2>/dev/null || lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1; do
  port=$((port + 1))
done
echo "$port" > "$dir/.dev-port"

{
  echo "# Generated by scripts/new-worktree.sh for worktree '$name'. Development database schema $schema."
  echo "# Every scheduled or sending job is off and no Outlook credential is present, so nothing real is touched."
  grep -Ev '^(DATABASE_URL|DIRECT_URL|MICROSOFT_[A-Z_]+|OUTLOOK_TOKEN_ENCRYPTION_KEY|EMPLOYER_CC_ADDRESS|DIGEST_TO|AUTOPILOT|DAILY_DIGEST|MAIL_SCAN_ENABLED|MAIL_INTAKE_SCAN|FOLLOW_UP_AUTO|FOLLOW_UP_AUTO_STAGE|EXPOSURE_MODE|DICE_CHROME_USER_DATA_DIR|EXPOSURE_CDP_URL)=' "$main_dir/.env"
  echo "DATABASE_URL=\"$url\""
  echo "DIRECT_URL=\"$url\""
  echo 'MAIL_SCAN_ENABLED="false"'
  echo 'MAIL_INTAKE_SCAN="off"'
  echo 'FOLLOW_UP_AUTO="off"'
  echo 'FOLLOW_UP_AUTO_STAGE="off"'
  echo 'AUTOPILOT="off"'
  echo 'DAILY_DIGEST="off"'
  echo 'EXPOSURE_MODE="off"'
} > "$dir/.env"
chmod 600 "$dir/.env"

# node_modules as an APFS clone of the main checkout's (near-instant, no extra disk until files differ).
# Only a branch whose lockfile differs installs, and with `npm ci`, which never rewrites the lockfile:
# a worktree must start with a clean `git status`, or an agent may commit a stray lockfile change.
if cmp -s "$main_dir/package-lock.json" "$dir/package-lock.json"; then
  cp -Rc "$main_dir/node_modules" "$dir/node_modules" 2>/dev/null || cp -R "$main_dir/node_modules" "$dir/node_modules"
else
  (cd "$dir" && npm ci --prefer-offline --no-audit --no-fund --silent)
fi
(
  cd "$dir"
  npx prisma generate >/dev/null
  npx prisma migrate deploy >/dev/null
  npx tsx scripts/seed-dev.ts
)

echo "Worktree:  $dir  (branch feature/$name)"
echo "Database:  schema $schema in contractor_agent_dev"
echo "Dev server: cd \"$dir\" && npm run dev:wt   → http://localhost:$port"
echo "Remove:    ./scripts/remove-worktree.sh $name"
